### ISSUE TITLE
[Qiskit Installation] Trouble with Qiskit installation? - Ask Here

### ISSUE THREAD

**Issue by fvarchon** [qiskit-community/qiskit-camp-asia-19#17]
# Help Desk

If you are having trouble installing qiskit in your environment, add a comment below and we will help you.

### 2/ Information
**Qiskit version**: Stable or Master?
**Operating system**: ?
**Slack name** in qiskit.slack.com: ?

**Comment by ace314** [comment]
1/ Short description of your problem
It is just a minor problem. I cannot import Aer from qiskit; while BasicAer works fine to me. I think it's the problem similar to https://github.com/Qiskit/qiskit-aer/issues/112. But the solution in this issue  
failed to my case.
2/ Information
Qiskit version: Master. I installed all modules via pip install.
Operating system: win10
Slack name in qiskit.slack.com: Che Chiang

**Comment by atilag** [comment]
@ace314 I can help you here! Let's meet and see what's going on :)

**Comment by 1ucian0** [comment]
If you need to contact the coaches, please contact `@coaches` in `#qiskit-camp-asia` slack channel.

If you need help with qiskit installation or github/git, please contact `@support` in `#qiskit-camp-asia` slack channel.

**Comment by fvarchon** [comment]
Some people have problem installing qiskit with python 3.8.
Our recommendation is to installed it with python 3.7

**Comment by 1ucian0** [comment]
seems slack is being a better way to solve tech issues... closing it for now.

**Comment by Matt-Stypulkoski** [comment]
Documenting issue that came up 

1. `pip install qiskit` completes successfully
2. `import qiskit` fails, throws `ImportError: cannot find module named <module_name>`
3. <module_name> is shown in `pip list` and successfully installs if we try to pip install it
4. After looking in the `site-packages` folder, we do not see the actual module's folder, only see the .dist folder for that module
5. After doing `pip install <module_name> --no-cache`, the install successfully populates `site-packages` with the module's folder.
6. `import qiskit` works and python is able to find the module.

For the issue we specifically were dealing with, `marshmallow_polyfield` was the module that was throwing the error. It was only with `qiskit` version 0.13.0 and `marshmallow_polyfield` version 5.7

The reason the error was happening was because there was a cached .whl installation file for `marshmallow_polyfield` that pip was trying to install from, however that version only has a .tar.gz file to install from (https://pypi.org/project/marshmallow-polyfield/#files). So, once we put the `--no-cache` flag, pip ignored that cached file and installed the package correctly.
